spring:
  datasource:
    #url : jdbc:h2:mem:test
    url: jdbc:mysql://brawlstat.c3snsgqvsofs.ap-northeast-2.rds.amazonaws.com:3306/sys
    username: admin
    password: 6s8GJggs8q9Ol3biXsha
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:h2:tcp://localhost/~/jpashop
    #username: sa
    #password:
    #driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update 
    properties:
      hibernate:
        #show_sql: true
        #format_sql: true
        
server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript,application/json
    min-response-size: 500
  
#logging:
  #level:
    #org.hibernate.SQL: debug
    #org.hibernate.type: trace
   